apiVersion: v1
kind: Service
metadata:
  name: nats
  labels:
    component: nats
spec:
  type: NodePort
  selector:
    component: nats
  ports:
  - name: client
    port: 4222
  - name: cluster
    port: 6222
  - name: monitor
    port: 8222
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: nats
  labels:
    component: nats
spec:
  serviceName: nats
  replicas: 1
  updateStrategy:
        type: RollingUpdate
  template:
    metadata:
      labels:
        component: nats
    spec:
      containers:
      - name: nats
        imagePullPolicy: IfNotPresent
        image: nats:1.0.4
        ports:
        - containerPort: 4222
          name: client
        - containerPort: 6222
          name: cluster
        - containerPort: 8222
          name: monitor
        livenessProbe:
          httpGet:
            path: /
            port: 8222
          initialDelaySeconds: 10
          timeoutSeconds: 5
