apiVersion: v1
kind: Pod
metadata:
  name: qot-appbundle
  labels:
    component: qot
spec:
  volumes:
  - name: shared-sockets
    hostPath:
      # directory location on host
      path: /tmp/qot
      # this field is optional
      type: DirectoryOrCreate
  containers:
  - name: qot-sync-service
    image: qot-sync-service:latest
    imagePullPolicy: Never
    volumeMounts:
    - name: shared-sockets
      mountPath: /tmp
  - name: qot-timeline-service
    image: qot-timeline-service:latest
    imagePullPolicy: Never
    volumeMounts:
    - name: shared-sockets
      mountPath: /tmp
  - name: qot-coord-service
    image: qot-coord-service:latest
    imagePullPolicy: Never
    ports:
    - containerPort: 8502
      name: client
  - name: qot-helloworld
    image: qot-helloworld:latest
    imagePullPolicy: Never
    volumeMounts:
    - name: shared-sockets
      mountPath: /tmp
  