apiVersion: v1
kind: Pod
metadata:
  name: qot-appmqtt-python
spec:
  volumes:
  - name: shared-sockets
    hostPath:
      # directory location on host
      path: /tmp/qot
      type: DirectoryOrCreate
  containers:
  - name: qot-helloworld-mqtt
    image: 770301640873.dkr.ecr.us-west-2.amazonaws.com/qot-helloworld-mqtt:latest
    imagePullPolicy: Always
    #command: ["python", "/usr/local/bin/helloworld_mqtt.py"]
    #args: ["--cacerts", "/ca.crt", "--certfile", "/mqtt-client.crt", "--keyfile", "/mqtt-client.key", "--broker", "mqttserver-svc.default.svc.cluster.local"]
    volumeMounts:
    - name: shared-sockets
      mountPath: /tmp
    #- name: shared-files
    #  mountPath: /shared_files
  - name: dummy-mqtt-actor
    image: 770301640873.dkr.ecr.us-west-2.amazonaws.com/dummy-mqtt-actor:latest
    imagePullPolicy: Always
    #command: ["python", "/usr/local/bin/mqtt_dummy_actor.py"]
    #args: ["--cacerts", "/ca.crt", "--certfile", "/mqtt-client.crt", "--keyfile", "/mqtt-client.key", "--broker", "mqttserver-svc.default.svc.cluster.local"]
    #volumeMounts:
    #- name: shared-files
    #  mountPath: /shared_files
  - name: dummy-mqtt-sensor
    image: 770301640873.dkr.ecr.us-west-2.amazonaws.com/dummy-mqtt-sensor:latest
    imagePullPolicy: Always
    #command: ["python", "/usr/local/bin/mqtt_dummy_sensor.py"]
    #args: ["--cacerts", "/ca.crt", "--certfile", "/mqtt-client.crt", "--keyfile", "/mqtt-client.key", "--broker", "mqttserver-svc.default.svc.cluster.local"]
    #volumeMounts:
    #- name: shared-files
    #  mountPath: /shared_files
  imagePullSecrets:
  - name: awstest
