apiVersion: v1
kind: Pod
metadata:
  name: qot-appmqtt-python
spec:
  volumes:
  - name: shared-sockets
    hostPath:
      # directory location on host
      path: /tmp/qot
      type: DirectoryOrCreate
  containers:
  - name: qot-helloworld-mqtt
    image: qot-helloworld-mqtt:latest
    imagePullPolicy: Never
    volumeMounts:
    - name: shared-sockets
      mountPath: /tmp
  - name: dummy-mqtt-actor
    image: dummy-mqtt-actor:latest
    imagePullPolicy: Never
  - name: dummy-mqtt-sensor
    image: dummy-mqtt-sensor:latest
    imagePullPolicy: Never
